sonar.projectKey=mattermost-toggle-reviewer
sonar.projectName=Mattermost Toggle Reviewer
sonar.host.url=http://localhost:9012
sonar.token=sqp_40de1517ed87a9052364e7b1d3a78f1b1fa7d1cf
sonar.sources=server/channels/app,server/public/model
sonar.inclusions=server/channels/app/content_flagging.go,server/public/model/content_flagging_setting_request.go,server/public/model/content_flagging_settings.go
sonar.exclusions=**/*_test.go,**/vendor/**,**/mocks/**,**/enterprise/**
sonar.go.coverage.reportPaths=server/coverage.out
sonar.sourceEncoding=UTF-8
