sonar.projectKey=mattermost-toggle-reviewer
sonar.projectName=Mattermost Toggle Reviewer
sonar.host.url=http://host.docker.internal:9012
sonar.token=squ_76af51993ab2c2caa3694a8cf289e140642c2900
sonar.sources=channels/app,public/model
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=**/*_test.go,**/vendor/**,**/mocks/**,**/enterprise/**
sonar.sourceEncoding=UTF-8
