sonar.projectKey=mattermost-toggle-reviewer
sonar.projectName=Mattermost Toggle Reviewer
sonar.host.url=http://host.docker.internal:9012
sonar.token=sqp_fddd5d22999d3aad9b1fd80c4388663334fb9bea
sonar.sources=channels/app,public/model
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=**/*_test.go,**/vendor/**,**/mocks/**,**/enterprise/**
sonar.sourceEncoding=UTF-8
