sonar.projectKey=mattermost-toggle-reviewer
sonar.projectName=Mattermost Toggle Reviewer
sonar.host.url=http://host.docker.internal:9012
sonar.token=sqp_40de1517ed87a9052364e7b1d3a78f1b1fa7d1cf
sonar.sources=channels/app,public/model
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=**/*_test.go,**/vendor/**,**/mocks/**,**/enterprise/**
sonar.sourceEncoding=UTF-8
